# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4e7635ee9170d1658810540150506f8b49a851fbbbd4f85cd2764ee9624055bac30856363494bb65c9c5c15f56174da2af72ae9657b444cfab9ed8a0a2b4ddb

test:
  secret_key_base: 4690478586e645c04b136a07d835276432b19b6c3e8f52bdc642916f138216abd92fc2a5a503a5f7b63e9828a73446d03d320527450beac92c1589af544b055c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
